name: Reusable ERP Sync

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
    secrets:
      APP_ID:
        required: true
      APP_INSTALLATION_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v3

      - name: Authenticate as GitHub App
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Clone monorepo
        run: |
          git clone https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/cezarxo/erp-main.git temp-main
          cd temp-main
          git switch -c sync/${{ inputs.module_name }}/${{ github.run_number }}

      - name: Copy code into Modules/
        run: |
          rm -rf temp-main/Modules/${{ inputs.module_name }}
          mkdir -p temp-main/Modules/${{ inputs.module_name }}
          rsync -av --exclude=temp-main --exclude=.git ./ temp-main/Modules/${{ inputs.module_name }}

      - name: Commit and Push
        run: |
          cd temp-main
          git config user.name "ERP Sync Bot"
          git config user.email "bot@erp.com"
          git add Modules/${{ inputs.module_name }}
          git commit -m "🔁 Sync ${{ inputs.module_name }} module"
          git push origin sync/${{ inputs.module_name }}/${{ github.run_number }}

      - name: Create Pull Request
        run: |
          gh auth setup-git
          gh pr create \
            --repo cezarxo/erp-main \
            --title "🔁 Sync ${{ inputs.module_name }} module" \
            --body "Auto-synced via GitHub Actions." \
            --base develop \
            --head sync/${{ inputs.module_name }}/${{ github.run_number }}
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}